from tkinter import *
import time
def data():
    ttime=time.strftime('%r')
    dateformate=time.strftime("%a,%d %h %Y")
    standard_date=time.strftime("%d/%m/%y")
    labs.config(text=standard_date)
    labe.config(text=ttime)
    labh.config(text=dateformate)
    labs.after(200,data)
clock=Tk()
clock.title(' enri media ')
clock.geometry("500x300")
clock.config(bg="purple")
labh=Label(clock,font=("Time New Roman",40,"bold"),bg="purple",fg='yellow')
labh.place(x=40,y=40)
labs=Label(clock,font=("Time New Roman",40,"bold"),bg='purple',fg='yellow')
labs.place(x=40,y=120)
labe=Label(clock,font=("Time New Roman",40,"bold"),bg='purple',fg='yellow')
labe.place(x=40,y=200)
data()
clock.mainloop()
